#!/usr/bin/env python3
import os
import json
import lz4.block
from glob import glob
from pprint import pprint
import youtube_dl
import youtube_dl.utils


filename = glob('/home/patrick/.mozilla/firefox*/*.default-*/sessionstore-backups/recovery.jsonlz4')[0]
file = open(filename, 'rb')
magic = file.read(8)
json_data = json.loads(lz4.block.decompress(file.read()).decode('utf-8'))
file.close()
urls = [tab['entries'][tab['index']-1]['url'] for win in json_data['windows'] for tab in win['tabs']]


class logger(object):
    def debug(self, msg):
        pass
    def warning(self, msg):
        pass
    def error(self, msg):
        print(msg)

def progress_hook(d):
    if d['status'] == 'finished':
        print('Done downloading, now converting ...')

ydl_opts = {
    'format': 'bestaudio/best',
    'ignoreerrors': True,
    'postprocessors': [{
        'key': 'FFmpegExtractAudio',
        'preferredcodec': 'mp3',
        'preferredquality': '192',
    }],
    'logger': logger(),
    'progress_hooks': [progress_hook],
}
with youtube_dl.YoutubeDL(ydl_opts) as ydl:
    ydl.download(urls)
